# Site settings
title: "febbc"
url: "//achillesz.github.io"
paginate: 10 
gems: [jekyll-paginate]
author:
    name: achilles
    github:
    email:
    gitcafe:
    twitter:
    facebook:
    googleplus:
    weibo:
atom_path: /atom.xml
rss_path: /rss.xml

# Build settings
kramdown:
    input: GFM
redcarpet:
    extensions: ["fenced_code_blocks", "tables", "highlight", "strikethrough"]
permalink: /:year-:month-:day-:title/
assets_path: /assets
sass:
    sass_dir: assets/_sass
    style: :compressed

# comment
comments:
    provider: duoshuo
    duoshuo:
        name: febbc
        rcomments:
            num: 10
            avatar: 0
            time: 0
            title: 0
            admin: 1
            length: 26
# 网站统计
analytics:
    baidu:
        siteid:                             # 百度统计 js 代码后的字符串

